# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://alexey300479.github.io/dslib/"

git_url = "https://github.com/alexey300479/dslib/tree/master/"

def custom_doc_links(name): return None
